### PR TITLE
Fix update command allowing end date before start date 

### LINKED ISSUE #152: Update command allows for end date to be before start date
## Description
Update commands allows end date to be before the start date

## Steps to Reproduce
1. Create an event
2. update -ed [end date before start date]

## Expected Behavior
The event should not be updated and the end date should not be modified

image

image

### PR DESCRIPTION
**Pull request by michaelyql**
## Describe your changes

Update command should now throw an error if the end date is before start date. 

More tests need to be added for `UpdateCommand` and `UpdateCommandParser`
## Related Issues

Closes #152, #167

## Type of Change

Bugfix

## Checklist

- [x] Code follows project style guidelines
- [x] I have performed a self-review of my code
- [x] Code is commented where necessary, particularly in hard-to-understand areas
- [x] Tests have been added/updated
- [ ] Documentation has been updated (if applicable)
- [x] CI checks have passed

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/UpdateCommand.java [hunk 1]
```diff
@@ -53,6 +54,8 @@ public class UpdateCommand extends Command {
 
     public static final String MESSAGE_INDEX_OUT_OF_BOUNDS = "There is no event at this index";
 
+    public static final String ERR_END_DATE_BEFORE_START_DATE = "The start date must come before the end date";
```
Comment (marchjlim) [inline src/main/java/seedu/address/logic/commands/UpdateCommand.java:57]: Perhaps we should rename it `MESSAGE_ERR_END_DATE_BEFORE_START_DATE` or something along those lines, to be consistent with `MESSAGE_INDEX_OUT_OF_BOUNDS` ?

File: src/main/java/seedu/address/logic/commands/UpdateCommand.java [hunk 2]
```diff
@@ -167,4 +178,10 @@ public String toString() {
                 .add("removeIndices", removeIndices)
                 .toString();
     }
+
+    private void checkStartDateBeforeEnd(LocalDate sd, LocalDate ed) throws CommandException {
+        if (sd != null && ed != null && sd.compareTo(ed) > 0) {
```
Comment (marchjlim) [inline src/main/java/seedu/address/logic/commands/UpdateCommand.java:183]: Maybe we could use `requireAllNonNull` method, as we are using it in many other places of the code base. Helps with SLAP principle.

Comment (marchjlim) [reply src/main/java/seedu/address/logic/commands/UpdateCommand.java:183]: Also, instead of using compareTo, LocalDate has built in methods to check whether a LocalDate is before/after/same as another LocalDate.

**Review by marchjlim — CHANGES_REQUESTED** [review]
